Create database SMC proyecto;
Use SMC proyecto;
Create table categories (// los varchar son para expecificar y nombrar que tipo de movimiento es y su nombre , atravez de textos
    id_categoria INT primary key ,    // El int es como la fecha de publicacion del movimiento
    tipo movimiento varchar,// los varchar son para expecificar y nombrar que tipo de movimiento es y su nombre , atravez de textos
    nombre varchar );// los varchar son para expecificar y nombrar que tipo de movimiento es y su nombre , atravez de textos

    
